name: Daily Commit

on:
  schedule:
    # Runs every day at 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24ds3000090@ds.study.iitm.ac.in
        run: |
          echo "Daily update on $(date +'%Y-%m-%d %H:%M:%S')" >> update.txt
          git config --local user.email "24ds3000090@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git add update.txt
          git commit -m "Daily update on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

      - name: Push Changes
        run: git push
